---
title: annotations
bibliography: germanic-ai.bib
#nocite: '@pethes_war_2006'
# tables:
#   - tbl_qa: {file: "qa.qmd", num: 1}
#   - tbl-summary: {file: "results.qmd", num: 2}
title-meta: ""
---

{{< include _vars.qmd >}}

## notes on 
paper: @bsi_wie_2025   


<!-- `r tblcap<-paste0("Table ",params$tables$tbl_qa1$num,", BSI: annotations")` -->

```{r}
#| label: tbl_qa1
#| tbl-cap: "BSI: annotations"
#| echo: false
#| warning: false
#| eval: true

qa<-c("Wie KI unsere Sprache","yakura-llm")
m1<-tdf$paper==qa[1]

kdf<-data.frame(id=which(m1),annotations=tdf$a[m1])

knitr::kable(kdf)

```

## notes on 
paper: @yakura_empirical_2025   


<!-- `r tblcap<-paste0("Table ",params$tables$tbl_qa2$num,", Yakura, LLM influence: annotations")` -->
<!-- !expr 'tblcap2' -->
```{r}
#| label: tbl_qa2
#| tbl-cap: "Yakura, LLM influence: annotations"
#| echo: false
#| warning: false
#| eval: true

qa<-c("Wie KI unsere Sprache","yakura-llm")
m2<-tdf$paper==qa[2]

kdf<-data.frame(id=which(m2),annotations=tdf$a[m2])

knitr::kable(kdf)

```
