
## data
We built a corpus of the reddit r/schizophrenia thread (``` `r paste0("n =",length(tdb$obs$token)," tokens")` ```) and a reference corpus of r/unpopularopinion (``` `r paste0("n =",length(tdb$ref$token)," tokens")` ```). Both were pos-tagged using the R udpipe package (@wijffels_udpipe_2023) which tags according to the universal dependencies tagset maintained by @de_marneffe_universal_2021. Still the available data can only, within the pipeline of steadily growing the corpus and devising the noun distances developed be just a starting point from where with more datapoints statistical evaluation becomes relevant.  
The dataframe used for our model (actual: dataset 13) consists of ``` `r length(qltdf$token)` ``` distance datapoints (sample cf. Tab. \@ref(tab:data1) below) derived from the postagged corpus. Because the ranges of the url threads vary heavily between target and reference corpus, the distances are (in evaluation M1) normalised to the target corpus (cf. Fig. \@ref(fig:gplot1) for the raw vs. normalised distances comparison.) Outliers are excluded from the analysis since they very probably do not fulfill to can be counted as anaphoric references. We silently assume that all of the noun distances which are not by value excluded as outliers occur as anaphoric references. A manual annotation and close reading of the text would be necessary to exactly determine wether the references are associated at all. This may be the task for another qualitative evaluation of our quantitative study.


```{r data1,message=F,warning=F,echo=FALSE,tab.cap="data sample of distances df"  }
sample.df<-dfa[sample(1:length(dfa$dist),10),]
sample.df<-sample.df[sample.df$le.char<15,]
m1<-grepl("scaled",colnames(sample.df))
m<-grep("dist_",colnames(sample.df)[!m1])
sample.df[,m]<-round(sample.df[,m],0)
m<-grep("embed",colnames(sample.df))
sample.df[,c(m,which(m1))]<-round(sample.df[,c(m,which(m1))],2)
#sample.df[,which(m1)]<-round(sample.df[,which(m1)],3)
m<-colnames(sample.df)%in%c("author","lemma","position","sentence_id","text_id","is_anaphora","mention_order","le.char","next_position","xpos","next_url")
sample.df<-sample.df[,!m]
m<-grepl("range_",colnames(sample.df))
sample.df<-sample.df[,!m]
#colnames(sample.df)
#library(knitr)
library(kableExtra)

# kable(mtcars[1:10, ], caption = "Scrollable table") %>%
#   kable_styling(full_width = FALSE, position = "left") %>%
#   scroll_box(width = "100%", height = "auto")
knitr::kable(sample.df,row.names = F,booktabs = TRUE)%>%
    kable_styling(full_width = FALSE, position = "left",latex_options = "scale_down") %>%
  scroll_box(width = "100%", height = "auto")


```




