

```{r label=wcount<<model>>,echo=F,warning=F,message=F}
# knitr::knit_hooks$set(chunk = function(x, options) {
# #  if (!is.null(options$label_prefix)) {
#     options$label <- paste0(options$label,"_",model.n)
# #  }
# x
# # knitr::engine_output(options, x)
# })
#print(options$label)
# f<-list.files(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/paper"))
# library(readtext)
# fns<-paste0(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/paper/"),f)
# m<-grep("child|methods-ul.md|conclusion|draftpaper-ul.md",fns)
# t<-lapply(fns[m], function(x){
#   t<-readtext(x)$text
#   t<-gsub("```\\{.+```","",t)
#   c<-strsplit(t," ")
#   n<-length(unlist(c))
#   return(n)
# })
# #print(t[[3]])
# #writeLines(t[[3]],"countwds.txt")
# #f[2]
# swc<-sum(unlist(t))
```

## evaluation model: `r model.n`

### meta 
eval output data: `r dataset``r caption.ext`   

### parameter setting

```{r,label=modelexp<<model>>,echo=FALSE,warning=F,message=F}
mdf<-data.frame(value=unlist(model))
print(mdf)
```


### anova analysis
#### anova plain
formula: [``` `r anova.form` ```]

```{r,label=dfs1<<model>>,echo=FALSE,warning=F,message=F}
# legend<-data.frame(variable=c("target","q","det",paste0("q:",letters[1:6])),
#                    explanation=c("corpus","condition","antecedent POS==DET",rep("query condition",6)),
#                    values=c("obs,ref","a,b,c,d,e,f","TRUE,FALSE",
#                             ".*","this,that,those,these","the","a,an,any,some","my","his,her,their,your")
#                    )
# #library(kableExtra)
# 
# # k<-kable(legend,caption = "model vars")
# # k<-kable_styling(k,full_width = TRUE)
# # k
# kable(legend, caption = "model vars") #%>%
# #  kable_styling(full_width = TRUE)
s1<-eval.1$anova.plain
p.select<-c("target|target:q")
p.an<-s1[grep(p.select,rownames(s1)),]
#p.an
#cat("anova plain, formula: `",anova.form.l$pre.det,"`\n")
s1
```

#### anova of linear regression model
[`anova(summary(lmer))`]

```{r,label=dfs2<<model>>,echo=FALSE,warning=F,message=F}



s2<-eval.1$anova.lme
p.an.lm<-s2[grep(p.select,rownames(s2)),]
#p.an.lm
#cat("anova of linear regression model (below): [`anova(summary(lmer))`]\n")
s2
```

#### linear regression coefficients
formula: [``` `r lme.form` ```]

```{r,label=dfs3<<model>>,echo=FALSE,warning=F,message=F}
s3<-eval.1$lme
#cat("linear regression coefficients, formula: `",lmeform.l$pre.det,"`\n")
#print(s3, right = TRUE, width = 999)
#print(s3)
#options(max.print = 1000)  # Set higher limit
invisible(capture.output(
  suppressWarnings(
    suppressMessages(
      print(s3)
    )
  ), type = "message"
))
#print(s3)
coef<-s3$coefficients
### relations:
int<-coef[1,1]
#int
qv<-coef[9:(length(coef[,1])),1]
qvc<-qv
#qvc

qvc.ns<-strsplit(names(qvc),"q")
qvc.ns<-lapply(qvc.ns, function(x){
  return(x[2])
})
qvc.ns<-unlist(qvc.ns)
names(qvc)<-qvc.ns
#l<-length(qvc.ns[[1]])
qdiff<-int+qv
qmin<-qdiff<int
qvmin<-qv[qmin]
names(qvmin)<-names(qvc)[qmin]
#qvmin
```

### plots
```{r,label=boxplot1<<model>>,echo=F,warning=F,message=F,fig.cap=paste0("compare distances by corpus",caption.ext)}
# df1_no_outliers <- dfa %>%
#   group_by(target) %>%
#   filter(
#     dist >= quantile(dist, 0.25) - 1.5 * IQR(dist),
#     dist <= quantile(dist, 0.75) + 1.5 * IQR(dist)
#   ) %>%
#   ungroup()
d.sel<-paste0("dist",norm_target)
Y<-dfa[[d.sel]]
boxplot(Y~target,dfa,outline=F,notch=T,varwidth=T,ylab = d.sel)

```

```{r,label=barplot-mean<<model>>,echo=F,warning=F,message=F,fig.cap=paste0("mean distances over query/corpus",caption.ext)}
dfe<-eval.1$plot.md
m1<-which(colnames(dfe)%in%c("mean","median"))
dfe[,m1]<-round(dfe[,m1],0)
# m2<-m1[length(m1):1]
# m3<-c(1:(m1[1]-1),m2)
# dfe<-dfe[,m3]
plot.dist(dfe,"mean")
```


```{r,label=dfe-table<<model>>,echo=F,warning=F,message=F}
kable(dfe,caption = paste0("mean/median table for model: ",model.n),format="markdown")
```


```{r,label=barplot-median<<model>>,echo=F,warning=F,message=F,fig.cap=paste0("median distances over query/corpus",caption.ext)}
plot.dist(dfe,"median")
```

```{r, label=lmeplot<<model>>,echo=F,warning=F,message=F,fig.cap=paste0("distances relation",caption.ext)}
rmd.plot.lme(s3)
```

```{r label=gplot<<model>>,echo=F,warning=F,message=F,fig.cap="distances normalised vs. raw"}
d_sel<-ifelse(ref_target!="",ref_target,"all")
gplot.dist(dfa,d_sel)
```


