---
title: "draft: coherence & proposition observations in :schizophrenia: threads"
author: "st. schwarz"
date: "`r Sys.Date()`"
output: 
    bookdown::html_document2:
      base_format: tufte::tufte_html
      keep_md: true
      self_contained: true
    #fig_path: "plots/"
  # md_document:
  #   variant: markdown_github
  #   pandoc_args: ["--wrap=none"]
  #keep_md: yes
bibliography: /Users/guhl/Documents/GitHub/SPUND-LX/psych/HA/paper/psych.bib
nocite: '@*'
#keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
library(knitr)
library(kableExtra)
```

```{r child="/Users/guhl/Documents/GitHub/SPUND-LX/psych/HA/paper/draftpaper-ul.md"}

```

```{r child="/Users/guhl/Documents/GitHub/SPUND-LX/psych/HA/paper/child-data-001.Rmd"}

```

```{r child="/Users/guhl/Documents/GitHub/SPUND-LX/psych/HA/paper/methods-ul.md"}

```

```{r child="/Users/guhl/Documents/GitHub/SPUND-LX/psych/HA/paper/child-eval-001.Rmd"}

```

```{r child="/Users/guhl/Documents/GitHub/SPUND-LX/psych/HA/paper/conclusion-ul.md"}

```

-----

## literature
