
```{r setup_ext_top, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
library(knitr)
library(kableExtra)
#library(glue)
# knit_hooks$set(chunk = function(x, options) {
#   # If a label_prefix is provided, prepend it to the label
#   if (!is.null(options$label_prefix) && !is.null(options$label)) {
#     options$label <- paste0(options$label,"_",options$label_prefix)
#   }
#   x  # return chunk code unchanged
# })
```

```{css, echo=FALSE,eval=T}
/*table {
  width: 100% !important;
  
}*/
pre {
border: 1px solid black;
border-radius: 0.25rem;
background-color: rgba(0, 0, 0, 0.04);

}
```

```{r,echo=FALSE,warning=FALSE,message=FALSE}
#dataset<-7
#poster-ext-top

# render_child <- function(child_file, prefix) {
#   # Read the child
#   txt <- readLines(child_file)
#   # Substitute <<prefix>> placeholders with actual prefix
#   txt <- gsub("<<model>>", paste0("_M-",prefix), txt)
#   
#   # Write a temporary file
#   tmpfile <- tempfile(fileext = ".Rmd")
#   writeLines(txt, tmpfile)
#   
#   # Knit the child inline
#   res <- knit_child(tmpfile)
#   file.remove(tmpfile)
#   #return(res)
#   cat(res,sep = "\n")
# }
expand_child <- function(child, prefix) {
  tmpfile <- tempfile(fileext = ".Rmd")
  txt <- readLines(child)
  txt <- gsub("<<model>>", prefix, txt, fixed = TRUE)
  writeLines(txt, tmpfile)
  return(tmpfile)
}

#childB <- expand_child("child.Rmd", "A")
#childC <- expand_child("child.Rmd", "A")

```

# appendix
overall wordcount of paper: `r swc`.

## legende
```{r,label=legend,echo=FALSE,warning=F,message=F}

#print(caption.ext)
legend<-data.frame(variable=c("target","q","det","aut_id","lemma","range","embed.score",paste0("q:",letters[1:6])),
                   explanation=c("corpus","condition","antecedent POS==DET","author","lemma","url range of distance devised","semantic similarity score lemma vs. thread",rep("query condition",6)),
                   values=c("obs,ref","a,b,c,d,e,f","TRUE,FALSE","author hash","noun lemma","1..maxlength(urlthread)","0:1 (scaled 0:100)",
                            "any !{b,c,d,e,f}","this,that,those,these","the","a,an,any,some","my","his,her,their,your")
                   )
#library(kableExtra)

# k<-kable(legend,caption = "model vars")
# k<-kable_styling(k,full_width = TRUE)
# k
kable(legend, caption = "model vars",format="markdown")
```


```{r preparemodel1,echo=F,warning=F,message=F}
model.n<-1
model<-model.list[[model.n]]
source(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/prepare-model.R"),echo = F)
childA <- expand_child(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/paper/child-poster-ext.Rmd"), model.n)

```

## covariance effects in M1 {#covar}
```{r effects,echo=F,warning=F,message=F}
#dfe<-eval.1$plot.md
#print(eff.ex)
print(eff1.s)
```

```{r child=childA}

```

```{r preparemodel2,echo=F,warning=F,message=F}
model.n<-2
model<-model.list[[model.n]]
source(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/prepare-model.R"),echo = F)
childB <- expand_child(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/paper/child-poster-ext.Rmd"), model.n)
```

```{r child=childB}
#render_child(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/paper/child-poster-ext.Rmd"), model.n)

```

```{r preparemodel3,echo=F,warning=F,message=F}
model.n<-3
model<-model.list[[model.n]]
source(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/prepare-model.R"),echo = F)
childC <- expand_child(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/paper/child-poster-ext.Rmd"), model.n)

```

```{r,child=childC}
#render_child(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/paper/child-poster-ext.Rmd"), model.n)

```

```{r preparemodel4,echo=F,warning=F,message=F}
model.n<-4
model<-model.list[[model.n]]
source(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/prepare-model.R"),echo = F)
childD <- expand_child(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/paper/child-poster-ext.Rmd"), model.n)

```

```{r,child=childD}

```


```{r preparemodel6,echo=F,warning=F,message=F}
model.n<-6
model<-model.list[[model.n]]
source(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/prepare-model.R"),echo = F)
childF <- expand_child(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/paper/child-poster-ext.Rmd"), model.n)

```

```{r,child=childF}

```

\clearpage

## Selbständigkeit: benutzte Hilfestellung
In der vorliegenden Arbeit wurden keinerlei nicht erlaubte Hilfsmittel zur Erstellung von Inhalten verwendet. Die Benutzung von KI beschränkt sich auf (Tabelle):

```{r,label=kitable,echo=F,tab.cap="verwendete Hilfsmittel"}
med<-list(Hilfsmittel=c(
  "github copilot","chatgpt.com","claude.ai","deepseek.com","nomic-embed-text (model)"
),Verwendung=c(
  "Hilfe bei der Skripterstellung (R, Python) zur \nProgrammierung der Distanzenberechnung, semantic embeddings und statistischen Auswertung","dito","dito","dito","calculate semantic embeddings"
))
med<-data.frame(med)
#knitr::kable(med,caption = "benutzte Hilfsmittel",format="markdown")
library(kableExtra)

# kable(mtcars[1:10, ], caption = "Scrollable table") %>%
#   kable_styling(full_width = FALSE, position = "left") %>%
#   scroll_box(width = "100%", height = "auto")
wrap_df <- function(df, width = 25) {
  data.frame(
    lapply(df, function(col) {
      # Only wrap character or factor columns
      if (is.character(col) || is.factor(col)) {
        sapply(as.character(col), function(x)
          paste(strwrap(x, width = width), collapse = "\n"))
      } else {
        col
      }
    }),
    stringsAsFactors = FALSE,
    check.names = FALSE
  )
}

library(knitr)

# kable(
#   wrap_df(med, width = 30),
#   format = "markdown"
# )
if (is_html_output()) {
knitr::kable(
  med,
  format = "html",
  table.attr = 'style="word-wrap:break-word; white-space:normal; width:100%;"'
)
} else if (is_latex_output()) {
kable(med, format = "latex", booktabs = TRUE, escape = FALSE) %>%
  kable_styling(latex_options = "hold_position") %>%
  column_spec(2, width = "10cm")  # wraps text in column 2
}
```

-----
\clearpage

## references
literature used and alii...   
