# _config.yml
title: SPUND-LX
tagline: LX alii
description:
url: "https://esteeschwarz.github.io/SPUND-LX"
baseurl: "/SPUND-LX" # if using project site, empty string if using user site

theme: jekyll-theme-chirpy

# Chirpy specific configurations
timezone: Europe/Berlin
lang: en
twitter:
  username: 
github:
  username: esteeschwarz

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Exclude these from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - .git
  - .gitignore