---
title: paper
---
# intro
## abstract
...
## preliminary
since we do not really get on information concerning the actual workflows of the content creation to the DCL pages, we will try to propose a more general pipeline to that based on our experiences with publishing. we will introduce possible alternatives to the actual (assumed) workflow and setup and give short insight into what is possible and under which circumstances.

## status quo
generally the momentary website seems not to be updated very much and although providing a friendly user experience lacks of content that would be integrating the introduced projects development i.e. you are presented a few projects related to linguistics but if you want to explore these deeper or keep updated with research results you realize that its often not more than a teaser with no follow up.

one reason for that as we assume might be a complicated workflow of delivering content or a workflow which does not allow project members to actively participate in content creation besides delivering finalised documents which then are integrated. say it appears to be a rather static process of content creation, not really adapted to the fluidity of academic research processes which tend to be in a progress-state for long time until results are published.

but namely the processs and progress of a project is what interests people who dive into scientific research. in times of fluid knowledge being key to understanding the world around one individum, static knowledge production (printed books in contrast to open source datasets and complex interfaces for data exploring or visualising or just uptodate papers and presentations) is one great barrier to open research to the public. the formats most frequently consumed are short knowledge bites in a nice environment. that doesnt mean researchers should not publish seriously, but - if using websites as media at all in times of youtube, tiktok etc. science channels - these websites do have to provide a minimum impression of being uptodate.

## what's the news
so what is it about a website that gives the reader the impression he is well informed with science news from today? surely a timeline that has not ended a year ago. as blog entries use to display the post date of the contribution mostly automatically, the blog format (which doesnt have to wake reminiscences to a diary at all) seems to be a good choice. normally the content of such a blog based website is fed from a server database to where content is posted via a webclient (web based user interface with more or less convenient editing and layout functionality). that approach affords that there is existing an admin level to the website that grants access to users and maintains the overall functionality of databases and backend (the server side of the blog). an often used and easy customizable backend for blog sites is wordpress but there are more open source and paid alternatives; the FU backend used for the current DCL sites seems to be provided by justrelate.com, a closed enterprise solution. And thats why...

## the git alternative
the usually well known windows philosophy boils down to "security by obscurity". well known in contrast to all elaborate approaches by the other providers of operating systems. the same may be said about content management systems which may be secure of being just not open sourced, and the same may be said about website content in general which can be transparent or disclosed.