---
title: workflow
---

## 16523
### 1
ich stehe jetzt vor der herausforderung, diesen beitrag (project page as 2nd layer site in dcl multisite layout) so convenient wie möglich zu veröffentlichen.

#### options
```{mermaid}
%%| label: fig-workflow-pub
%%| fig-cap: “publishing process options diagram”
%%| fig-alt: “Flowchart showing the publishing workflow"


graph TD

CR[create content] -->
dcl[in blog repo]
CR-->wd[in working repo]
dcl-->se[single post]
dcl-->ml[multilayer]
se-->fm[content format markdown, no python/R embedding or complex sites. restricted to jekyll render]
ml-->fmm[content may include complex page built from RMarkdown, Quarto or Python notebooks or any other framework]
o2[option 2]
```

#### preliminary: setup, status quo

```{mermaid}
%%| label: fig-setup
%%| fig-cap: “publishing process setup status quo”
%%| fig-alt: “Flowchart showing the current publishing workflow"

graph TD

s1[CONTENT]-->
dcl[jekyll site: dcl]
wd[working dir: spund-lx]
dcl-->p1[post display]-->
p2[2nd layer: project display]
wd-->p2
s1-->wd
```

#### goal: integrate new project page in blog

```{mermaid}
%%| label: fig-howto
%%| fig-cap: “publishing process forward”
%%| fig-alt: “Flowchart showing the workflow to integrate new content"

graph TD

s1[CONTENT: quarto page]-->
dcl[jekyll site: dcl: essais folder]
wd[working dir: GIT]-->wd2[spund-lx/lx-public/HA/DCL/pages]-->level1[complete quarto site folder including .qmd and quarto.yml]
level1-->ch[changes]-->r1[trigger rendering process]-->
git1[render via github actions]-->p2
r1-->srv1[render on target server]-->updcl[update DCL essais]-->p2
dcl-->p1[post entry]-->l1[link to 2nd layer: project page]-->p2
p2[2nd layer: project display]
ch-->rloc[docs rendered locally]-->p2
r1-->p2
wd-->csv[.csv metadata table of essais]-->ch-->chk1[is the project on DCL]-->pdcl1[yes]
s1-->wd
pdcl1-->r1
pdcl1-->rloc
chk1-->pdcl0[no]-->crp[create project page]-->crman[manually]
crp-->crcsv[on base of metadata.csv]-->csv-->pub1[publish]-->p2
```

#### todo: next steps to project page

```{mermaid}
%%| label: fig-todo
%%| fig-cap: “publishing process next todo”
%%| fig-alt: “Flowchart showing the next steps to integrate new content"

graph TD

crcsv[create .csv metadata table]-->
item[new project item]
wf[update render git workflow]-->wf1[to fire on changes in]-->csv[.csv metadata table]
crcsv-->csv-->item-->inc[includes]-->meta-->m1[render dir relative to working dir]
meta-->m2[tags]
meta-->m3[cats]


```

### 2
#### issues
there's premises we have to clear off before developing to great extend

- if it will be (and thats not sure) possible at all to use github as storage and render platform that would deploy the pages to an FU server where the DCL page is hosted. there can be administrative concerns about providing or hosting the backend at github with everybody able to read the source code of the site. this should generally be no issue because there doesnt have to be stored any material exceeding what is displayed as html anyway thus accessible, but coming from this,

```{r}
#| echo: false
#| output: false


if (Sys.info()["sysname"] == "Darwin") {
  m.binary <- "./mermaid-int"
} else if (Sys.info()["sysname"] == "Linux") {
  m.binary <- "./mermaid-lx"
}

md_to_mermaid <- function(md_text,target,labels) {
    print(labels)
      print(getwd())

  ifelse(!is.null(labels),prel<-paste0("%%","|"," ",labels),pre<-"")
  preamble<-ifelse(target=="quarto","```{mermaid}\n","")
  post<-ifelse(target=="quarto","\n```","")
 # preamble<-""
  result <- system2(
    # command = "/Users/guhl/Documents/GitHub/le-rust/essais/mermaid/target/debug/./mermaid",
    command = m.binary,
    input = md_text,
    stdout = TRUE,
    stderr = TRUE
  )
#  result<-system2("./mermaid", liste,TRUE,TRUE)
  print(prel)
  paste0(preamble,paste(prel,collapse = "\n"),"\n\n",paste(result, collapse = "\n"),post)
}

list<-"
- options to avoid the github hosting service are:
  - to render the pages completely on the contribuer device and deploy only html rendered pages to the restricted FU server -userpage level with no administrative user at the project level-
    - affords the contribuer to install render services on device
    - contribuer only pushes pages to site
    - edited source stays on device
  - to use a page hosting server -or userpage level- which allows for admin tasks like installing basic render services -which here would be jekyll, ruby and quarto- and to maintaining these services
    - contribuer needs to edit and push the markdown source which is rendered on the FU server apres
    - affords admin poition for maintaing the packages server side"

#mermaid<-md_to_mermaid(list,"quarto")
#cat (mermaid)
labels<-c("label: fig-premise","fig-cap: contribute options")
print(labels)
mermaid<-md_to_mermaid(list,"quarto",labels)
cat (mermaid)
```


`r md_to_mermaid(list,"quarto",labels)`


