---
title: "germanic languages drafts"
date: "2025-11-15"
categories: [expose,linguistics]
tags: [LX,sociolinguistics,HA,shibboleth,AI speech,register]
bibliography: /Users/guhl/Documents/GitHub/SPUND-LX/germanic/HA/germanic-exc.bib
nocite: '@*'
url: "https://esteeschwarz.github.io/open-lx/posts/germanic-001"
description: "germanic languages paper drafts"
link-citations: true
github-repo: "esteeschwarz/SPUND-LX/tree/main/germanic"
format:
  pdf:
    latex_engine: xelatex  # default
    fig-pos: "H" # Forces images to appear exactly where they are included
    # mainfont: Georgia
    # mainfont: Georgia
    mainfont: 'Noto Serif'
    #mainfont: 'Computer Modern Roman'
    font-size: 12
    #cite-method: biblatex
    colorlinks: true
        #  \newcommand{\he}[1]{{\hebrewfont #1}}
    #      \newcommand{\he}[1]{\bgroup\textdir TRT{\hebrewfont #1}\egroup} # wks rtl+ivrit
    include-in-header: rtl.tex

    # header-includes: |
    #  \usepackage{fontspec}
    #  \newfontfamily\ipafont{Arial Unicode MS}
    #  \newcommand{\ipa}[1]{{\ipafont #1}}
    #  \usepackage[margin=1in]{geometry}
    #  \usepackage{fvextra}
    #  \fvset{breaklines=true, breakanywhere=true}
    #  \usepackage{polyglossia}
    #  \setmainlanguage{english}
    #  \setotherlanguage{hebrew}
    #  \newfontfamily\hebrewfont{Noto Serif Hebrew}[Script=Hebrew]
    #  \newcommand{\he}[1]{\bgroup\textdir TRT{\hebrewfont #1}\egroup}


  html:
    theme:
      - cosmo #litera
      - brand
    # mainfont: 
    #   - Noto Sans
    #   - Noto Serif
    monofont: Menlo
    #font: Courier
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <!-- HTML simply prints the inner text -->
        <!-- 16482.snc -->
        <script type="application/latex">
        \newcommand{\he}[1]{#1}
        </script>
---

```{r,echo=F,eval=T}
pdfsrc<-""
if(!knitr::is_latex_output())
  pdfsrc<-'load pdf <a href="../../essais/germanic/shibboleth-a.pdf">here</a>'
he <- function(text) {
  if (knitr::is_latex_output()) {
    paste0("\\he{", text, "}")
  } else {
    text
  }
}
#cat(pdfsrc)
```

::: {.content-visible when-format="html"}

load pdf [here](index.pdf)

:::

# index
## sonderzeichentest
Hebrew test: (\he{שִׁבֹּלֶת}, cf. @sefaria_judges_2025)

Mixed: English `r he("שלום ")` world.

IPA: ...Anyone who pronounces it [pɛʟɛχɪʟ] and not [pɛʀɛχɪʟ]...

```{r child="/Users/guhl/Documents/GitHub/SPUND-LX/germanic/HA/abstract-ul-q-pl.md"}

```



{{< include abstractB-ul.md >}}

# References
<!--\clearpage-->
