---
title: "xtitle: coherence & presuppositions observations in :schizophrenia: threads"
author: "st. schwarz"
date: "`r Sys.Date()`"
output: 
    bookdown::html_document2:
      base_format: tufte::tufte_html
      keep_md: true
      self_contained: true
    #fig_path: "plots/"
  # md_document:
  #   variant: markdown_github
  #   pandoc_args: ["--wrap=none"]
  #keep_md: yes
bibliography: psych.bib
nocite: '@*'
#keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra)
```

```{css, echo=FALSE,eval=F}
table {
  width: 100% !important;
}
```

```{r}
#dataset<-7
```

```{r,src,echo=F,warning=F,message=F,results='hide',fig.keep='none'}
#eval.n<-7
dataset<-7
source(paste0(Sys.getenv("GIT_TOP"),"/SPUND-LX/psych/HA/eval-003.R"),echo = F)
```

# top
eval output M`r dataset`

## legende
```{r,legend,echo=FALSE,warning=F,message=F}
legend<-data.frame(variable=c("target","q","det",paste0("q:",letters[1:6])),
                   explanation=c("corpus","condition","antecedent POS==DET",rep("query condition",6)),
                   values=c("obs,ref","a,b,c,d,e,f","TRUE,FALSE",
                            ".*","this,that,those,these","the","a,an,any,some","my","his,her,their,your")
                   )
#library(kableExtra)

# k<-kable(legend,caption = "model vars")
# k<-kable_styling(k,full_width = TRUE)
# k
kable(legend, caption = "model vars",format="markdown")
```

## anova analysis
### anova plain, formula: ``` `r anova.form.l$pre.det` ```
```{r,dfs1,echo=FALSE,warning=F,message=F}
# legend<-data.frame(variable=c("target","q","det",paste0("q:",letters[1:6])),
#                    explanation=c("corpus","condition","antecedent POS==DET",rep("query condition",6)),
#                    values=c("obs,ref","a,b,c,d,e,f","TRUE,FALSE",
#                             ".*","this,that,those,these","the","a,an,any,some","my","his,her,their,your")
#                    )
# #library(kableExtra)
# 
# # k<-kable(legend,caption = "model vars")
# # k<-kable_styling(k,full_width = TRUE)
# # k
# kable(legend, caption = "model vars") #%>%
# #  kable_styling(full_width = TRUE)
s1<-eval.1$anova.plain
p.select<-c("target|target:q")
p.an<-s1[grep(p.select,rownames(s1)),]
#p.an
#cat("anova plain, formula: `",anova.form.l$pre.det,"`\n")
s1
```

### anova of linear regression model: [`anova(summary(lmer))`]

```{r,dfs2,echo=FALSE,warning=F,message=F}



s2<-eval.1$anova.lme
p.an.lm<-s2[grep(p.select,rownames(s2)),]
#p.an.lm
#cat("anova of linear regression model (below): [`anova(summary(lmer))`]\n")
s2
```

### linear regression coefficients, formula: ``` `r lmeform.l$pre.det` ```
```{r,dfs3,echo=FALSE,warning=F,message=F}
dfe<-eval.1$plot.md
s3<-eval.1$lme
#cat("linear regression coefficients, formula: `",lmeform.l$pre.det,"`\n")
s3$coefficients
coef<-s3$coefficients
### relations:
int<-coef[1,1]
qv<-coef[9:13,1]
qvc<-qv
names(qvc)<-letters[2:6]
qdiff<-int+qv
qmin<-qdiff<int
qvmin<-qv[qmin]
names(qvmin)<-names(qvc)[qmin]
#qvmin
```
## plots
```{r boxplot1,echo=F,warning=F,message=F,fig.cap="compare distances by corpus"}
# df1_no_outliers <- dfa %>%
#   group_by(target) %>%
#   filter(
#     dist >= quantile(dist, 0.25) - 1.5 * IQR(dist),
#     dist <= quantile(dist, 0.75) + 1.5 * IQR(dist)
#   ) %>%
#   ungroup()
boxplot(dist~target,dfa,outline=F,notch=T,varwidth=T)

```

```{r,barplot-median,echo=F,warning=F,message=F,fig.cap="median distances over query/corpus"}
plot.dist(dfe,"median")
```

```{r,barplot-mean,echo=F,warning=F,message=F,fig.cap="mean distances over query/corpus"}
plot.dist(dfe,"mean")
```

```{r lmeplot,echo=F,warning=F,message=F,fig.cap="distances relation"}
rmd.plot.lme(s3)
```

-----

# REF
literature used and alii...   


