## evaluate imageability
### dataset 1 {#eval-dat-1}

- data: 
  - filename: clip_results.parquet (Ivan Nenchev)
  - language: english 
  - textform: guided interview
  - dataform: exploded clip scores per token
  - additional: 
    - lexical diversity score
    - 1stPPronoun rate

```{r}
#| warning: false
#| echo: false
#| label: clip-dens
#| fig-cap: "clip score density plot"

### wks., proceed from here:
# print(getwd())
load("df4_lim.RData")
###############################################################
#library(tidyr)
#library(dplyr)
library(ggplot2)
library(lme4)
library(lmerTest)
#print(colnames(df4_lim))
#print(head(df4_lim))

# dff4 <- df4_lim %>%
#   unnest_longer(cl_score)
# dff4 <- df4_lim %>%
#   select(TN, text_chunk, group, ld, fstPPr_rate, cl_score) %>%
#   unnest_longer(cl_score)
# #colnames(dff4)[1]<-"cl_score"
### base R unnesting
# Get the lengths of each list element
# list_lengths <- sapply(df4_lim$text_chunk_clips, length)

# # Expand rows
# dff4 <- df4_lim[rep(seq_len(nrow(df4_lim)), list_lengths), ]

# # Flatten the list column
# dff4$cl_score <- unlist(df4_lim$text_chunk_clips)

# Reset rownames
# rownames(dff4) <- NULL
# #colnames(dff4)[grep("text_chunk_clips",colnames(dff4))]<-"cl_score"
# colnames(dff4)[grep("filename",colnames(dff4))]<-"TN"
# print(unique(dff4$TN))
ggplot(data = dff4, aes(x = cl_score,fill = group)) +
  geom_density(alpha=0.5) +
  labs(title = "Density Plot", x = "clip score", y = "Density") +
  theme_minimal() 

```

```{r, lme1}
#| warning: false
#| echo: false
#| label: lme1

lm6<-lmer(cl_score~group+(1|TN)+(1|text_chunk)+ld+fstPPr_rate,dff4)
#lm4<-lm(cl_score~group,dff)
# summary(lm1)
print(summary(lm6))



```