name: Render quarto (survey-eval)
'on':
  push:
    branches: main
    paths: eval/nprg-eval/**
  workflow_dispatch: ~
jobs:
  render:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/quarto-r-tex:latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Render Quarto site
      run: quarto render eval/nprg-eval -P reload:false
    - name: Upload rendered HTML directory
      uses: actions/upload-artifact@v4
      with:
        name: q-open
        path: q
  deploy:
    runs-on: ubuntu-latest
    needs: render
    steps:
    - name: Download rendered directory
      uses: actions/download-artifact@v4
      with:
        name: q-open
        path: q-open
    - name: Check out Repo B
      uses: actions/checkout@v4
      with:
        repository: esteeschwarz/open-lx
        token: ${{ secrets.TARGET_REPO_PAT }}
        path: target
    - name: Copy into Repo B/public
      run: cp -r q-open/* target/essais/
    - name: Commit and push
      run: |
        cd target
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Update quarto sites: survey-eval" || echo "No changes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
    - name: Check out Repo C
      uses: actions/checkout@v4
      with:
        repository: esteeschwarz/DC-LX
        token: ${{ secrets.TARGET_REPO_PAT }}
        path: target
    - name: Copy into Repo C/public
      run: cp -r q-open/* target/essais/
    - name: Commit and push
      run: |
        cd target
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Update quarto sites: survey-eval" || echo "No changes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
