project:
  type: website
  pre-render: "prerender.R"
  # post-render: "postrender.R"
  output-dir: ../output/pages/004
# date: '`r format(Sys.time())`'
date: "2026-04-08"
csl: chicago-author-date-17th-edition.csl

# author: esteeschwarz
title-meta: ""
resources:
    - "*.bib"
    - "*.csv"
website:
  title: "004"
  navbar:
   left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: SS26
        menu: 
          - textur001.qmd
          - nietzsche001.qmd
          - lki-index.qmd
          - lxtech001.qmd
          - lfg-index.qmd
          - str-index.qmd
      - text: arkkiv
        menu:
          - href: https://userpage.fu-berlin.de/stschwarz/links?title=dclx&ref=play
            text: "DC-LX (new)"
          - href: https://userpage.fu-berlin.de/stschwarz/links?title=adaskool&ref=play
            text: "ada-school (olde)"
          - href: pdfpaper/001/uwolf.qmd
            text: reference-test
          - href: ../test/samling.html
            text: playtest
      - glossar.qmd

      # - text: "Download"
      #   menu:
      #     - href: report.pdf
      #       text: "Download PDF"
   right:
      - snc.qmd
      - href: https://github.com/esteeschwarz/SPUND-LX/
        icon: github

format:
  # gfm: default
  html:
    theme: 
      - cosmo
      - brand
    #code-overflow: wrap
    css: assets/styles.css
    toc: true
    toc-depth: 3
    toc-expand: true

  pdf:
      keep-tex: false
      keep-intermediates: false
      toc: false
    #   template: pdf-template.tex
    #   latex_engine: xelatex  # default lualatex
    #   latex-tinytex: false
      filters:
        - at: pre-ast
          path: assets/ipa-3.lua
      fig-pos: "H" # Forces images to appear exactly where they are included
    #   mainfont: 'Free Sans'
      font-size: 11
      colorlinks: true
      citecolor: cyan

      include-in-header: 
        - assets/lualoani.tex
        - assets/footer-header.tex
      include-before-body: assets/go-head.tex
        # - paper.tex
        #   pdf-engine: lualatex
    #   header-includes:
    #     - \newcommand{\docfoot}{$params.foot$}
    #     - \newcommand{\docmeta}{$meta$}
# filters:
#   # - assets/commands.lua
#   # - assets/luaipa.lua
#   - assets/cmeta-ipa.lua
# filters:
#   - at: pre-ast
#     path: assets/cmeta-ipa.lua
logoleft: assets/fadenlogo-fwb.png
logoright: assets/dcl-head-niemand.png
  # pdf:
  #   include-in-header:
  #     - text: |
  #         \usepackage{fvextra}
  #         \DefineVerbatimEnvironment{cell-output cell-output-stdout}{Verbatim}{
  #         breaklines=true,
  #         breakanywhere=true,
  #         fontsize=\small
  #         }
  #         \makeatletter
  #         \AtBeginDocument{
  #           \fvset{
  #             breaklines=true,
  #             breakanywhere=true,
  #             fontsize=\small
  #           }
  #         }
  #         \makeatother
  #         \usepackage{fancyvrb}
  #         \RecustomVerbatimEnvironment{verbatim}{Verbatim}{breaklines=true,breakanywhere=true}

execute:
  echo: true
  # freeze: false
  freeze: true
  
code-overflow: wrap
