project:
  type: website
  output-dir: ../output/pages/004
date: "2026-04-02"
# author: esteeschwarz
title-meta: ""
website:
  title: "004"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - pdfpaper/001/uwolf.qmd
      - text: "Download"
        menu:
          - href: report.pdf
            text: "Download PDF"

format:
  gfm: default
  html:
    theme: 
      - cosmo
      - brand
    #code-overflow: wrap
    css: styles.css
  pdf:
      keep-tex: true
      keep-intermediates: true
    #   template: pdf-template.tex
    #   latex_engine: xelatex  # default lualatex
    #   latex-tinytex: false
      filters:
        - at: pre-ast
          path: assets/ipa-3.lua
      fig-pos: "H" # Forces images to appear exactly where they are included
    #   mainfont: 'Free Sans'
      font-size: 11
      colorlinks: true
      include-in-header: 
        - assets/lualoani.tex
        - assets/footer-header.tex
      include-before-body: assets/go-head.tex
        # - paper.tex
        #   pdf-engine: lualatex
    #   header-includes:
    #     - \newcommand{\docfoot}{$params.foot$}
    #     - \newcommand{\docmeta}{$meta$}
# filters:
#   # - assets/commands.lua
#   # - assets/luaipa.lua
#   - assets/cmeta-ipa.lua
# filters:
#   - at: pre-ast
#     path: assets/cmeta-ipa.lua
logoleft: assets/fadenlogo-fwb.png
logoright: assets/dcl-head-niemand.png
  # pdf:
  #   include-in-header:
  #     - text: |
  #         \usepackage{fvextra}
  #         \DefineVerbatimEnvironment{cell-output cell-output-stdout}{Verbatim}{
  #         breaklines=true,
  #         breakanywhere=true,
  #         fontsize=\small
  #         }
  #         \makeatletter
  #         \AtBeginDocument{
  #           \fvset{
  #             breaklines=true,
  #             breakanywhere=true,
  #             fontsize=\small
  #           }
  #         }
  #         \makeatother
  #         \usepackage{fancyvrb}
  #         \RecustomVerbatimEnvironment{verbatim}{Verbatim}{breaklines=true,breakanywhere=true}

execute:
  echo: true
code-overflow: wrap
