# tmeta: $testmeta$
# date: '`r format(Sys.time())`'
date: "2026-04-20"
toc: true
toc-depth: 3
title-meta: ""
bibliography: litKI.bib
cmeta: |
  class: [16431] Literatur und KI ::
  tutor: marlene schwarz ::
  term: SS26
  snc: 16172.2 
arkiv: 16222.common-yml
# foot: the anarkkiv lankalevikki worksheet collection >> <https://ada-sub.dh-index.org/blog>
cfoot: |
  [duumy foot collection](https://stschwarz.userpage.fu-berlin.de/links/?title=paperfoot&ref=paper-temp)
###