---
title: Lit / KI
subtitle: "no"
format: html
toc: true
toc-depth: 3
toc-expand: true

# tmeta: $testmeta$
# date: '`r format(Sys.time())`'
date: "2026-04-20"
title-meta: ""
bibliography: litKI.bib
cmeta: |
  class: [16431] Literatur und KI ::
  tutor: marlene schwarz ::
  term: SS26
  snc: 16172.2 
#[<< back to online paper <<](https://esteeschwarz.github.io/DC-LX/essais/papers/010/)  
#  arkiv: [<< the anarkkiv lankalevikki worksheet collection >>](https://stschwarz.userpage.fu-berlin.de/links/?title=paperfoot&ref=paper-temp)
arkiv: 16162.tiny
# foot: the anarkkiv lankalevikki worksheet collection >> <https://ada-sub.dh-index.org/blog>
cfoot: |
  [duumy foot collection](https://stschwarz.userpage.fu-berlin.de/links/?title=paperfoot&ref=paper-temp)
---
```{r,echo=F,eval=F}
#print("engine on...")
#val <- quarto::quarto_metadata$get("meta")
#meta <- knitr::metadata
#params <- meta$
#val<-params$tmeta
# t<-"class: [16719] Nietzsche und Nietzscherezeption ::
#   tutor: friederike günther ::
#   term: SS26
#   snc: 16163.1"
# tl<-  unlist(strsplit(t,"::"))
# val.f<-"fixed val"
# val.c<-"{{< meta testmeta >}}"
# val.c<-"{{< meta cmeta >}}"
#val.d<-strsplit(val.c,"::")
#val.d<-unlist(val.d)
#print(typeof(val.c))
#print(val.c)
#print(val.d)
#print(tl)
#print(dim(val.d))
# cat(val.c)
```

::: {.content-visible when-format="html"}

{{< meta cmeta >}}
:::
{{< include _gitcom.qmd >}} 

::: {.content-visible when-format="html"}

-----

> [index](index.qmd) / Lit KI

-----
:::
<!-- this page deprecated just for link conserve reason, dont edit -->
```{r,echo=F,eval=T}
print("engine on...")
```


# index
1. samling: margin notes general > [open](lki-qa.qmd){.btn .btn-cat}
2. summary on kybernetik introduction > [open](lki-001.qmd)
3. bajohr - AI authorship et al. > [open](lki-002.qmd)

