---
title: "subject - authorship - value in LLM generated texts"
subtitle: "Literatur und Künstliche Intelligenz"
#date: '`r format(Sys.time())`'
date: '2026-05-25'
# toc: true
# toc-depth: 3
# toc-expand: true

categories:
   - gpt
   - llms
   - training prospectives
   - authorship
   - model collaps
   - bajohr
metadata-files:
  - _quarto-common-lki.yml
---

<!-- in pdf generated with lua filter -->
::: {.content-visible when-format="html"}
{{< meta cmeta >}}
:::

{{< include _gitcom.qmd >}} 

::: {.content-visible when-format="html"}
-----

> [Lit KI](lki-index.qmd) / bajohr

-----
:::

```{r,echo=F,eval=T}
print("engine on...")
```

#### snc
- 16231.1234

- [x] sent
- [ ] final

# intro
nachdem ich einige texte von hannes bajohr (@bajohr_subjekt_2024, @bajohr_berlin_2023, @bajohr_glaube_2017) gelesen habe, stellen sich mir mehrere fragen, die so oder so ähnlich sich scheinbar schon angekündigt hatten im laufe der auseinandersetzung mit den themen des seminars. durch bajohr wurde ein grundlegendes problem hier einmal ausformuliert, dem in der literaturwissenschaft zentrale bedeutung zukommt: das (subjekt) d/ autor/ oder authorship sowie damit verbunden dann subjektivität-objektivität, verantwortung, zukunft der literatur unter dem aspekt künstlicher intelligenz.

## play on perspectives
ich hatte parallel angefangen, über konsequenzen, perspektiven LLM-generierter sprache (unabhängig zuerst von literatur, sondern eher allgemein) nachzudenken und bin schnell zu seit einiger zeit diskutierten theorien zum sog. *model collaps* gelangt, von dem bei nicht sorgfältig beobachteten entwicklungsbedingungen für sprachmodelle wohl im groszen/ganzen ausgegangen werden kann. (@gu_sigma_2026, @shumailov_ai_2024, @piantadosi_modern_2024, @chatgpt_how_2026). Wir streben anscheinend derzeit mit einiger sicherheit auf einen punkt zu, wo die modelle nicht mehr in der lage sein werden, überhaupt noch sinnvollen output zu erzeugen der noch irgendwie an dem orientiert ist, was für uns *die wirklichkeit* ist, da sie ca. in einer uns (seminar) schon bekannten feedbackschleife den content, den sie selbst creiert haben, konsumieren und darauf nächste generationen ihrerselbst trainieren. in einem ersten einfachen versuch habe ich ein simples model auf ein corpus trainiert und schon in der 2. generation, die mit +0.1% generiertem content trainiert wurde, war eine abnahme der entropy (also information) und faktisch 3 types weniger im output zu verzeichnen (89 unique chars vs. 86 unique chars). > ([see output](model-collapse-lki.qmd))

### entropy
wir haben im rahmen der kybernetik sitzung bereits über *entropie* gesprochen, aber hier nochmal zur verdeutlichung im context KI: die menschliche sprache (als teil genuin menschlichen strebens - lebens) zeichnet sich durch ihre hochgradige organisation aus, die es menschen ermöglicht, sie (regelhaft) zu erlernen, ihre strukturen zu erkennen; syntaktische, semantische, pragmatische regeln in der kommunikation anzuwenden, um (erfolgreich) zu kommunizieren. *erfolgreich* heiszt in der linguistik nur, dasz beide (gesprächs)teilnehmer/ kenntnisse der regeln anzuwenden in der lage sind und sich grob gesagt *verstehen*. es geht dabei immer um *information* die ausgetauscht wird, egal ob wahre oder falsche (@bense_theorie_1962 : 19f, [lesen](https://esteeschwarz.github.io/SPUND-LX/pages/004/textur-qa.html#:~:text=#anchor_01)). abnehmende entropie bedeutet ca. zunehmende information, da die *zeichen*, die ausgetauscht werden, nicht mehr ungeordnet im (raum) existieren, sondern sprachlich organisiert sind - eine ordnung aufweisen - die der entropie entgegensteht, welche stets nach dem nullpunkt an ordnung bzw. ausgeglichenheit, ausgewogenheit, gleichmäszigkeit... strebt; einem zustand, in dem keinerlei energie mehr vorhanden ist oder ausgetauscht wird weil es keine energieunterschiede mehr gibt.

und hier kommt auch oben angedeutetes problem auf den tisch: sagt bajohrs *berlin, miami* zb. etwas (neues) aus bzw. teilt es information über das hinaus, was in dem von ihm trainierten model als vektorraum bereits bekannt, statistisch ausgewertet, hinreichend modelliert ist? ist das neue, was durch sein prompting hervorgerufen wird, neu im sinne einer jemals-ungesagten-erkenntnis (die man von eine/ menschl. autor/ erwarten würde, preiszugeben in form von literatur) oder nicht vielmehr neu hier nur die methode, die die literatur schaffte und der ganze ansatz eben, das *konzept* des buches zum primat der erzählung zu erheben? überwinden wir hier möglicherweise das diktum *show-dont tell* zugunsten eines *show* ***how***-*dont tell* ***how***?

bajohr gibt die nischenhaftigkeit des produkts zu bedenken, aber ich denke, wenn literatur selbst (die erzählung) nichts mehr zu bieten hat (auszer künstlichen austauschbaren content) und dennoch als literatur wahrgenommen werden kann, dann ist der technische entstehensprozess umso spannender[^1], und das vielleicht nicht nur für nerds...

[^1]: analog: die museale, pädagogische aufwertung historischer kulturtechniken, an denen heute vielleicht nicht mehr primär das *produkt* interessiert (wie zur zeitgenössischen anwendung) sondern die (zb. historisch-soziale) verortung der technik/tätigkeit [e.g. webstuhl].

# references
