---
title: kybernetik
subtitle: "Norbert Wiener - Regelung und Nachrichtenübertragung im Lebewesen und in der Maschine"
# format: html
# tmeta: $testmeta$
# date: '`r format(Sys.time())`'
date: "2026-05-16"
title-meta: ""
bibliography: textur.bib
metadata-files:
  - _quarto-common-textur.yml

# cmeta: |
#   class: [16416] Text und Textur. Vom Webstuhl bis zu Large Language Models ::
#   tutor: jan lietz ::
#   term: SS26
#   snc: 16162.1  
# #[<< back to online paper <<](https://esteeschwarz.github.io/DC-LX/essais/papers/010/)  
# #  arkiv: [<< the anarkkiv lankalevikki worksheet collection >>](https://stschwarz.userpage.fu-berlin.de/links/?title=paperfoot&ref=paper-temp)
# arkiv: 16162.tiny
# # foot: the anarkkiv lankalevikki worksheet collection >> <https://ada-sub.dh-index.org/blog>
# cfoot: |
#   [duumy foot collection](https://stschwarz.userpage.fu-berlin.de/links/?title=paperfoot&ref=paper-temp)
---

::: {.content-visible when-format="html"}
{{< meta cmeta >}}
:::
{{< include _gitcom.qmd >}} 
::: {.content-visible when-format="html"}

-----

> [Textur](textur001.qmd) / kybernetik

-----
:::

#### snc
- 16223.1

- [x] sent
- [ ] final

```{r,echo=F,eval=T}
print("engine on...")
```

{{< include _lki-001b.qmd >}} 

## und texturen...
das war grundlegendes[^1] aus der "einführung" der kybernetik (@wiener_kybernetik_1992), die von ihm noch einmal für ein breiteres publikum umgearbeitet und eingang in @wiener_human_1950 fand. und wo kommen unsere :texturen: ins spiel?

wir können durchaus beim webstuhl bleiben, der ja als zentrales thema das seminar ausmacht. wir haben über den jaccard mechanismus schon einiges gehört und hier fängt es auch mit der kybernetik an. durch die einführung automatisierter abläufe in die technik [des webens], die sich damit weitgehend von der manuellen steuerung durch den menschen emanzipierte, kommen auch fragen nach dem [vielleicht: subjektcharacter] dessen, was eigentlich den vorgang steuert und das, was dabei von wem genau *gewebt* wird, ins spiel. wir haben es an dieser stelle nicht mehr mit menschlich-individueller bzw. im eigentlichen sinne *kreativer* (schöpferischer, künstlerischer) technik, sondern mit auf algoritmen, prozessual-routinierten regeln beruhenden schritten zur herstellung des produkts zu tun, die a) unendlich fein ausdifferenziert, b) unendlich weit vorausgedacht sowie c) unendlich haltbar gespeichert und abgerufen werden können [in potenz.] kann man dies von der abgelösten menschlichen fertigkeit des (webens) ebenso sagen? wahrscheinlich eher nicht. die hier hergestellte textur muss im gegensatz zur traditionellen ein element beinhalten, das un-menschlich ist; das irgendwie aus der zeit herausgelöst sein muss, die dem menschen eigentümlich ist.[^2] mit unendlich verfügbarem material und energie liesze sich eine textur vorstellen, die tausend menschenjahre lang sich selbst webte und (das universum?) umspannte.

### feedback
wir stellen uns weiterhin vor, der maschinismus ist [der kybernet] in der lage, sein eigenes produkt fortwährend zu reflektieren, aufgrund der statusrückmeldungen seinen *output* zu modellieren, sich selbst dazu anzulernen, das produkt zu optimieren. am ende (des lernprozesses) würde (der teppich) vielleicht nicht mehr viel mit dem zu tun haben, was (d. programmierer* ) im kopf gehabt hat, als den algoritmus sich ausdachte. es würde vielleicht nicht mal mehr ein teppich sein, sondern u.u. etwas, das das *ideal* eines teppichs wäre, die *Idee vom Teppich*. aber das geht zu weit, nestcepas...

die texturen, die wiener referiert und die er immer wieder mit *dem äther* querführt, einem auch zu seiner zeit fragwürdigen, aber immernoch attraktiven konzept eines alles umspannenden, alles durchdringenden, undefinierbaren elements, das *die welt im innersten zusammenhält* -

> (... a curious, rigid, but invisible medium known as the ether, which, at the time, was supposed to permeate the atmosphere, interstellar space and all transparent materials [[...](https://esteeschwarz.github.io/SPUND-LX/pages/004/textur-qa.html#:~:text=interstellar)])

... haben durchaus metaphysische qualitäten. in ihnen wird das unsichtbare sichtbar. der vorgestellte welt-teppich wäre am ende ein abbild der welt selbst, wenn man das konsequent zuende denkt. (ca., der kybernet: ach schau, das ja auch interessant, das fehlte noch..., na dann ab in den teppich damit :)

#### caveats
apropos feedback: bei wiener [!sic 1948] klingt die vorstellung der feedback loop noch durchaus vielversprechend. was aber passiert (entgegen auch meiner o.a. vorstellungen der :idee: ), wenn unser model fortwährend sich selbst referiert, wird aktuell unter dem stichwort *model-collapse* untersucht und sieht ca. künftige generationen von language models (also immernoch kyberneten) voraus, deren output

1. zunehmend vorraussehbar (predictable)
2. weniger divers
3. weniger ausgeglichen
4. und zunehmend eindimensional

wird. 

das zeigt sich dann in zunehmenden musterwiederholungen, eindimensionalen phrasen, weniger types (unique words/tokens) und generell einer abnahme der entropie dh. die annahme eines höher organisierten (aber nicht mehr mensch-sprachlich strukturierten) zustands, der konsequent auf erstarrung hinausläuft, weil die späteren generationen eine weitgehend (inzestuöse beziehung) mit dem eigenen output eingehen. in texturbegriffe übersetzt würde unser teppich langsam den weg von einem farbenfrohen (universum der begriffe) hin zu einem diachromen gewebe aus eigentlich nur 2 zuständen, nämlich strom/nichtstrom, nehmen. wir haben es hier mit einer entropie im entgegengesetzten sinne des natürlichen verständnisses zu tun. indem die vielseitigkeit des teppichs abnimmt, die wahrscheinlichkeit von mustern höher wird, desto weniger information kann er uns geben.

@wiener_human_1950 : 21

> Just as entropy is a measure of disor­ganization, the information carried by a set of mes­sages is a measure of organization. In fact, it is possible to interpret the information carried by a message as essentially the negative of its entropy, and the negative logarithm of its probability. That is, the more probable the message, the less information it gives. Cliches, for example, are less illuminating than great poems.

d.h. dieser von einem nahe collabierenden model produzierte teppich is no news at all.

> see: [model-collaps](https://esteeschwarz.github.io/SPUND-LX/pages/004/model-collapse-textur.html) for a nice experiment on modeling with a small corpus.

[^1]: ich musz zugeben, ich komme mit den beiden seminaren literatur/KI und textur etwas durchenander, es lohnt sich aber auch (von hier) einmal [dort](lki-index.qmd) zu schauen, was sich so überschneidet...

[^2]: das wären dann auch die fragen in die runde, vielleicht mit inverse focus: 1. was ist das spezifische (momentum), das eine explizit nicht künstliche textur von einer solchen unterscheidet? 2. was wären weitere begriffe aus dem noch-handwerklich/manuellen bereich, die sich auf nicht-künstliche textur (im weitesten sinne, literarische texturen/gewebe/strukturen einschlieszend) im gegensatz zu künstlicher anwenden lieszen? an welchen stellen wir es mit faszbaren im gegensatz zu abstrakten oder virtuellen strukturen zu tun?

# references

