#20231226(11.01)
#14424.xmas-riddle.essai3
#########################
x1<-"Einer, der allerlei stibitzte
Es gab Phasen, da war er streng mit sich selbst. Etwa, als er diesen Satz schrieb: „Körperliche Vorzüge besitze ich keine.“ Tatsächlich wird ihm auf Steckbriefen eine schwächliche Gestalt bescheinigt. Aber er sollte es allen zeigen. Die Voraussetzungen sind dafür nicht günstig. Er wird als fünftes von 14 Kindern in eine bitterarme Familie hineingeboren, ergattert trotzdem einen Ausbildungsplatz, der eine Chance auf Bildung und Aufstieg verheißt und verliert ihn wieder, wegen eines kleinen Diebstahls. Leider nicht die einzige Missetat, als Häftling scheint die kriminelle Karriere vorgezeichnet. Aber gegen alle Wahrscheinlichkeit kriegt er die Kurve, hat Erfolg, wird richtig reich und von sehr vielen Menschen außerordentlich geschätzt. Wie kann sich jemand derart ändern? Eine Theorie ist, das hat er gar nicht. Er hat es lediglich geschafft, seine übersteigerte Fantasie zu zähmen, indem er sie nicht mehr auslebt, sondern in der Traumwelt belässt. Meistens jedenfalls. Wenn er nicht gerade versucht, die Leute glauben zu machen, das sei alles wahrhaftig und echt."

x2<-"Eine, die alles wegspülen wollte
Als sie jung war, konnte man ihr in der Metropole an verschiedenen Orten begegnen. Auf dem Pflaster eines Boulevards, in einem schicken Lokal, womöglich gar im Wartezimmer eines Arztes. Immer sah sie blendend aus. Kein Wunder, dass sich viele darum rissen, ihr nah zu sein. Bisweilen ließ sie es zu, nie war es lange, einmal zu sandig. Muße hielt sie nicht aus, nippte hier und dort. Einen, dem sie besondere Impulse verdankte, traf sie im Café einer Hauptstadt, unweit eines Mausoleums. Damals wusste sie noch nicht, wie sehr sie sich mit Leid und Tod beschäftigen würde. Das geschah auf eigenen Wunsch, aus Überzeugung gar. Schulterfreie Abendkleider passten nicht mehr, Stöckelschuhe waren überflüssig. Der Boden, den sie betrat, war oft uneben, scharfkantig, manchmal rot. Was die Gesuchte sah, teilte sie bald mit vielen in der Ferne. Die konnten rasch weiterblättern, zu Dessous oder Cocktailkleidern. Bei ihr war alles im Kopf, wie eingebrannt. Es musste weggespült werden. Wieder und wieder. Half nichts. Der Nachlass der Gesuchten zeigt, warum.
"
x3<-"Einer, der auf der Flucht war
Schon in Schulzeiten fielen seine Gedichte den Lehrern auf. Es zog ihn mit Macht in die Hauptstadt, und durch die Vermittlung eines gemeinsamen Freundes nahm er einen Briefkontakt mit einem um zehn Jahre Älteren auf, der sich dort bereits einen Ruf in der literarischen Welt erworben hatte. Die Verbindung zwischen beiden, die weit mehr war als eine rein poetische Symbiose, prägt die Literatur bis heute. Die stürmische Beziehung zwischen dem jungen Enfant terrible und dem Älteren führte zur Flucht der beiden Dichter ins Ausland, doch dort kam es zu einer Gewalttat. Als er etwa 20 Jahre alt war, kehrte der Gesuchte der Dichtkunst abrupt den Rücken. So, als hätte sie ihm nichts bedeutet. Er begann ein neues Leben als Abenteurer und Geschäftsmann. London und Stuttgart, wo er Deutsch lernen wollte, waren die ersten Stationen einer längeren Odyssee. Er verdingte sich unter anderem als Soldat einer Kolonialarmee und als Angestellter einer Handelsfirma. Ein Tumor zwang ihn zur Rückkehr in die Heimat. Doch da war es für eine Heilung schon zu spät."
x4<-"Eine, die einfach sitzen blieb
Kerle waren auf diese famose Idee nicht gekommen, eine Frau musste ihnen weibliche Gedanken erst plausibel machen. Die Quintessenz: Wer auf sich achtet, ist im Vorteil. Doch als diese pfiffige Frau, die den meisten Männern ohnehin immer ein gutes Stück voraus war, das Ding erstmals vorschlug, waren die Kerle durchaus angetan. Sie hatte es ihnen aufgeschrieben, darin war sie firm. Die Überlegung dahinter leuchtete selbst in einer Männergesellschaft ein. Denn fortan konnten auch die Herren der Schöpfung einfach sitzen bleiben und behielten trotzdem alles im Blick. Den bahnbrechenden Vorschlag übernahm ein Kollege zwei Jahre später und installierte fest, was zuvor nur als Vorschlag existierte, und weitere drei Jahre danach übernahm die Industrie das Ding serienmäßig. Das ist über hundert Jahre her. Heutzutage nicht auszudenken, wäre diese Überlegung einer forschen Frau nicht umgesetzt worden. Gewinn machten andere damit, ihr aber bleibt der Thron als Vorreiterin und Pionierin weiblicher Unabhängigkeit."
x5<-"Einer, der schnell genug hatte
In einem Land, gut zwölf Flugstunden von hier, konnten die Menschen nicht glauben, was sie sahen. Und für Außergewöhnliches waren sie ja hergekommen in jenem Herbst. Aber das war zu verrückt, ganz und gar verdreht, aber nicht verwackelt. Was Jahrzehnte funktioniert hatte, galt nichts mehr. Nur, weil jemand aus einem Küstenland kam und sein eigenes Ding machte. Auch in seiner Heimat hatte man den Kopf geschüttelt. Er lief Gefahr, aussortiert zu werden, wurde zu den Clowns gewünscht. Ärzte warnten Kinder, derlei Unsinn nachzumachen. Zudem war der Gesuchte schon so lädiert, dass er nicht in den Krieg ziehen konnte. Experimente im Garten seiner Eltern sollen ihn auf seine Idee gebracht haben. Dort, wo er geboren wurde, ist man stolz darauf, immer eine Lösung zu finden. Er glaubte an sich und blieb eigensinnig. Während andere sich nach Erfolgen lange feiern ließen, hatte er schnell genug. Er wollte nicht im Mittelpunkt stehen und füllte seinen klugen Kopf lieber mit Zahlen. Er wurde 76 Jahre alt."
x6<-"Einer, der mit Akzent sprach
Als er das Licht der Welt erblickte, gab es das Land, in dem sein Geburtsort heute liegt, noch nicht. Auch den Namen, unter dem er weltberühmt wurde, sucht man in den Taufregistern der Stadt vergeblich. Der ursprüngliche Familienname wäre für sein neues Heimatland zu kompliziert gewesen, so blieb er nur den Vornamen treu. Ohnehin nahm sein Leben einen Weg, der für ihn, eine geborene Landratte, nicht gerade nahelag. Wohl grenzte die alte Heimat an ein Meer, aber zur ersten Station seiner maritimen Karriere wurde es nicht. Während derer brachte er es sogar zum Kapitän, obwohl er sich neben all dem nautischen Wissen zugleich eine neue Sprache aneignen musste. Die sprach er zeitlebens mit Akzent, schriftlich wusste er sich aber bald so gut darin auszudrücken, dass jeder, der seine Herkunft nicht kannte, ihn für einen Muttersprachler halten musste. Schließlich gab er den alten Beruf zugunsten seiner neu gefundenen Fähigkeiten ganz auf, aus dessen Erfahrungen er aber weiterhin gern schöpfte."
x7<-"Eine mit scharfer Zunge
Ihre politischen Fundraising-Partys waren legendär. Sogar für den Klobesuch in ihrem Haus mussten die linken Gäste zahlen. Als Tochter aus verarmtem Adel hatte sie von der Mutter sparen gelernt. Eine Schule hat sie nie besucht, Schreiben konnte sie trotzdem. Und wie! Bestsellerautorin und Journalistin ist sie im fortgeschrittenen Alter geworden, eine Miss Marple der Investigation - die Leute unterschätzten sie. Ihre größte Waffe: ihre scharfe Zunge und ihr Humor. Beide hatte sie im Wettstreit mit den Schwestern gewetzt, von denen einige als Erwachsene ans andere Ende des politischen Spektrums drifteten. Sie selbst hat sich vor nichts und niemand gefürchtet. Schon gar nicht vor der amerikanischen Polizei. Das Selbstbewusstsein, mit dem die Aristokratin groß geworden war, setzte sie am anderen Ende der Welt mit größter Selbstverständlichkeit als Aktivistin ein. Vor der Familie war sie weggerannt –ihrer Partei blieb sie treu, über alle Zweifel hinaus. Ihre Chuzpe machte sie dann zum Star der Studentengeneration. Und zur Heldin von Harry Potter-Autorin J.K. Rowling."
x8<-"Einer, der im Zickzack lief
Und dann gibt es noch den klassischen Wendehals, eine zwielichtige Gestalt, ob nun skrupellos, innerlich schwach, klassisch opportunistisch oder verschlagen, schwer durchschaubar auf alle Fälle. Schon beim Familiennamen war er sich nicht ganz eins, griff auch zum Pseudonym. Aus bürgerlichem Milieu stammend, ruderte er mal links, kajakte dann rechts, wurde zum Raubritter im nationalen Rausch. Im folgenden zweiten Getümmel gelang ihm eine weitere Kehrtwende, ehe er – zwischen allen Stühlen hängend – eine neue Heimat im anderen Deutschland suchte und fand. Roh, dumm und blind, hatte ihn ein ehemaliger Weggefährte Ende der Weimarer Republik gegeißelt. Der Krug geht so lange zum Brunnen, bis er bricht, heißt es in einem Sprichwort. Dieser hier landete, nach seinem Zickzacklauf eines rasenden Hasen, ehrenhalber auf einem Friedhof literarischer Säulenheiliger. Und die Nachwelt kann sich Gedanken darüber machen, was ein Mitläufer ist, was ein Konjunkturritter und was ein nicht ganz wahrhaftiger Kerl.
"
x9<-"Eine, die Waffen kaufte
In ihrem Heimatland ist die Frau eine Legende, schon wegen der dramatischen Wende. Ursprünglich führte sie das Leben einer Landedelfrau aus wohlhabendem Haus, die es sich in ihrem Schloss, das der Zeit entsprechend mehr eine Burg war, gemütlich machen konnte. Aber sie wurde in unruhige Zeiten hineingeboren, ihre Heimat geriet zum Zankapfel zwischen zwei mächtigen Herrscherhäusern. Da hieß es ein wenig lavieren, was ihrem Mann den Vorwurf des Hochverrates einbrachte. Doch sein Herrscher schien auf Versöhnung aus und lud ihn zu einem Turnier ein. Eine Finte, der Gatte wurde gemeuchelt, seine Ländereien beschlagnahmt. Da traf es sich, dass die Gesuchte über eigenes Vermögen verfügte, das sie nun zur Finanzierung ihrer zweiten Karriere nutzte, abseits von Minnesang und Handarbeit. Sie rüstete eine kleine Armee aus, zu Lande – und so will es wenigstens die Legende - zu Wasser, verpasste ihren Schiffen einen auffälligen Anstrich und kannte keine Gnade für jene, die sie für den Tod ihres Gatten verantwortlich machte. Was ihr den Ruf einbrachte, dem Namen nach ein Raubtier zu sein."
x10<-"Einer, der Finten setzte
Geboren wurde er in einer Stadt, die Einheimische stolz mit einem italienischen Juwel vergleichen. Schule, Studium, Doktorhut, eine glänzende Karriere bahnte sich an. Eine, mit der man viel Geld verdienen konnte. Doch die Zeiten waren nicht danach, er wurde anderswo gebraucht. Ohne Widerspruch folgte er. Wie aber sollte er umgehen mit den zwei Seelen in seiner Brust? Anfangs schien die eine prägend, doch das änderte sich. Er legte sich mit jenen an, die ihm langsam misstrauten. Wagte einiges nahe einer Stadt, in der sich viele gegen ihren Willen versammeln mussten. Eine Finte nach der anderen dachte er sich aus. Seine Vorgesetzten in der Ferne schäumten, doch kam er ohne Bestrafung davon. Als alles vorbei war, wurde abgewogen, wie das nun war mit seinen zwei Seelen. Das Ergebnis war niederschmetternd für ihn. Seinen ersten Beruf durfte er nicht mehr ausüben. In einem anderen Land konnten sie das nicht nachvollziehen und handelten im Grünen. Da war er schon lange tot.
"
priddle<-"~/Documents/GitHub/R-essais/SPUND/play/"
xdf<-rbind(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10)
colnames(xdf)<-"text"
xdf<-data.frame(xdf)
k<-1
for(k in 1:length(xdf[,1])){
  xns<-rownames(xdf)
  writeLines(xdf$text[k],paste0(priddle,"riddle.",xns[k],".txt"))
}
keys<-read.csv("keywords.csv",skip = 2)
terms<-read.csv("terms.csv",skip = 2)

write_clip(terms$Item)


