library(stringdist)
library(stats)
amatch(c("hello","g'day"),c("hi","hallo","ola"),maxDist=2)
ar<-c("beige","foo","bar","boo","baz","ball","feige")
query
cc<-unlist(strsplit(corpus,"\\s+"))
ar<-c(query,cc[1:1000])
hc<-stringdistmatrix(ar)
#plot(hclust(hc),ar)
plot(hclust(hc))
head(hc)
p<-amatch("drick",cc[1:100000])
cc[(p-10):(p+10)]
d<-stringdist("psych",cc[1:10000])
max(d)
m<-min(d)
s<-m:(m+2)
s1<-d%in%s
cc[s1]
