---
title: "interaction-copresence (replic)"
author: "esteeschwarz"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# replication study
## preliminaries
Q1: Imo, W. (2024). Digital vermittelte Interaktion ohne Kopräsenz: Immer noch Interaktion? In Handbuch Sprache und Digitale Kommunikation (Bd. 23, S. 249–268). Walter de Gruyter GmbH. <https://doi.org/10.1515/9783110744163-012>   

## method

```{r}
query<-"okay|oki|oke|okey|okee|okidoki|o.k.|okk|okkk"
limit<-"That|that|That's|that's|that\031s|I'm|It's|it's|Its|its"

```
----

Q2: <https://www.english-corpora.org/glowbe/>   
> no export possible of results   

Q3: <https://corpora.linguistik.uzh.ch/annis/?id=4d1db244-fe3d-4b2d-a47b-04d985f06ea0>   
> no export possible of results   

Q4: <https://corpora.linguistik.uzh.ch/annis/?id=ae12da87-b757-4a43-ba92-183194f43b11>   
> no export possible of results   

Q5: <https://corpora.linguistik.uzh.ch/annis/?id=a0fa2756-1342-4c69-a53d-21adca7819b9>   

Q6: <https://www.reddit.com/r/unpopularopinion/>


### ANNIS queries:
```{aql}
tok=‎/.*‎/ & 
tok=‎/.*‎/ & tok=‎/(okay|oki|oke|okey|okee|okidoki|o\.k\.|okk|okkk)‎‎/ & tok=‎/.*‎/ &
msg_id = ‎/.*‎/ &
msg_id = ‎/.*‎/ &
spk = ‎/.*‎/ &
spk = ‎/.*‎/ 
& #1 . #2 & #2 _=_ #5
& #2 . #3
& #3 . #4 & #3 _=_ #6
& #5 != #6 
& #2 _=_ #7 
& #4 _=_ #8
```

----

```{aql}
tok=‎/.*‎/ &  tok=‎/(okay|oki|oke|okey|okee|okidoki|o\.k\.|okk|okkk)‎/ &
msg_id = ‎/.*‎/ &
msg_id = ‎/.*‎/ 
& #1 . #2 
& #1 _=_ #3
& #2 _=_ #4
& #3 != #4 
```

----

```{aql}
tok=‎/.*‎/ &  tok=‎/(okay|oki|oke|okey|okee|okidoki|o\.k\.|okk|okkk)‎/ 
& #1 . #2 
```

----

### reddit comment extraction
- extract ```r query```
- limit to token within 4 from turn start
- limit to turn without ```r limit``` at turn start

#### results
```{r }

load("data/com.ok.extract.RData")
print(com.ok.extract)

```
