---
title: "büchner: rezeption & langeweile"
subtitle: "a georg buechner reception task"
description: "a georg buechner reception task"
author: "st. schwarz"
date: today
bibliography: buechner.bib
nocite: '@*'
categories: [AVL,buechner,reception]
cats_md: [essais,AVL]
tags_md: [AVL,buechner,reception]
site_link_text: "class presentation"
site_title: "006"
class: 'georg büchner. mara ruwe. WS25 FUB.'
task: 'session preparation to: buechner & reception'
input_dir: szondi/buechner/site
project_dir: szondi/buechner
ids: buechner-a

---

```{r}
#| echo: false
#| output: false
#| warning: false
source("create-slides.R") #todo: update docker first with package: stringi,yaml; updated, should work now.
```

```{r}
#| echo: false
#| output: false
#| warning: false
#| include: false

#stmp <- tempfile(fileext = ".qmd")
src<-"task001-ul.md"
### correct ulysses md issues
t<-readLines(src)
lines <- gsub("\\\\_", "_", t)
#md<-tempfile(fileext = ".md")
writeLines(lines,src)
#knitr::knit_child(tmp)

```

```{r}
#| echo: false
#| warning: false

tdf<-read.csv("qa.csv")
m2<-grep("(elancholi)",tdf$t)
m1<-grep("(.evolution)",tdf$t)

```

{{< include filename=task001-ul.md.qmd >}}

