name: "Build & Deploy Site from Rmd"

on:
  push:
    paths:
      - 'psych/HA/poster/*.Rmd'
      - '_config.yml'
      - '_layouts/**'
      - '_includes/**'
      - '.github/workflows/**'
      - 'docs/trigger.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
    #  R_LIBS_USER: ~/.local/lib/R/site-library
      R_LIBS_USER: /home/runner/work/_temp/Library
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false  # If using Chirpy as a submodule

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Restore R package cache
      uses: actions/cache@v4
      with:
        path: ${{ env.R_LIBS_USER }}
        key: r-${{ runner.os }}-lib
        restore-keys: |
          r-${{ runner.os }}-


    - name: Install required R packages
      run: |
        mkdir -p "$R_LIBS_USER"
        Rscript scripts/r-dependencies.R

    - name: Save updated R package cache
      uses: actions/cache/save@v4
      with:
        path: ${{ env.R_LIBS_USER }}
        key: r-${{ runner.os }}-lib

    - name: Render all Rmd files to _posts/
      run: |
        mkdir -p _posts
        for file in $(find docs -name '*.Rmd'); do
          fname=$(basename "$file" .Rmd)
          Rscript -e "rmarkdown::render('$file', output_format = 'md_document', output_file = paste0('../_posts/', format(Sys.Date(), '%Y-%m-%d-'), '$fname.md'))"
        done

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v4

    - name: Set up Ruby & Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Build Jekyll site
      run: bundle exec jekyll b -d "_site${{ steps.pages.outputs.base_path }}"
      env:
          JEKYLL_ENV: "production"

    - name: Upload site artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_site${{ steps.pages.outputs.base_path }}"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4